--文件传输日志表
DROP TABLE filetranslog CASCADE CONSTRAINTS;
CREATE TABLE filetranslog
(
  JLXH        NUMBER(10)    NOT NULL,
  XTXH        NUMBER(2)     NOT NULL,
  XTMC        VARCHAR2(50)  NULL,
  YHDM        VARCHAR2(10)  NOT NULL,
  OPERATION   VARCHAR2(20)  NOT NULL,
  CZSJ        DATE          NULL,
  JQM         VARCHAR2(50)  NULL,
  IPADDRESS   VARCHAR2(15)  NULL,
  NICADDRESS  VARCHAR2(12)  NULL,
  FILEGROUPID VARCHAR2(10)  NOT NULL,
  FILEPATH    VARCHAR2(200) NOT NULL,
  FILENAME    VARCHAR2(200)  NULL,
  FILESIZE    NUMBER(10)    NULL,
  VERSION     VARCHAR2(20)      NULL,                      --版本 
  CONSTRAINT PK_FILETRANSLOG PRIMARY KEY(JLXH)
);

DROP SEQUENCE SEQ_FILETRANSLOG_JLXH;
CREATE SEQUENCE SEQ_FILETRANSLOG_JLXH START WITH 1;
CREATE INDEX IDX_FILETRANSLOG_CZSJ ON FILETRANSLOG(CZSJ);