--系统信息表
DROP TABLE xtxxb;
CREATE TABLE xtxxb 
(
  XTXH      NUMBER(1)         NOT NULL,
  XTMC      VARCHAR2(50)      NOT NULL,
  VERSION   VARCHAR2(10)      NOT NULL,
  CONSTRAINT PK_XTXXB PRIMARY KEY(XTXH)
)tablespace JZGLXT;

INSERT INTO XTXXB VALUES(1,'急诊管理系统','010');
COMMIT;
INSERT INTO XTXXB VALUES(3,'图书馆管理系统','001');
COMMIT;
