--用户组表
DROP TABLE yhz;
CREATE TABLE yhz
(
  XTXH     NUMBER(2)  	NOT NULL,
  YHZXH    NUMBER(2)  	NOT NULL,
  YHZMC    VARCHAR2(20) NOT NULL,
  YHZDJ    NUMBER(1)    NULL,
  CONSTRAINT PK_YHZ PRIMARY KEY(XTXH,YHZXH)
)tablespace JZGLXT;

