--公用代码表
CREATE TABLE gydmb
(
    DMLB      VARCHAR2(10)         NOT NULL,   --代码类别
    DMXH      NUMBER(10)           NOT NULL,   --代码序号
    DMMC      VARCHAR2(50)         NULL,       --代码名称
    SRM       VARCHAR2(10)         NOT NULL,   --输入码
    BZ        VARCHAR2(30)         NULL,       --备注
    TS        VARCHAR2(30)         NULL,       --提示
    SYCS      NUMBER(10) DEFAULT 0 NULL,       --使用次数
    PXXH      NUMBER(10)           NULL,       --排序序号
    CONSTRAINT PK_GYDMB PRIMARY KEY(DMLB,DMXH)
)tablespace JZGLXT;

CREATE INDEX IND_GYDMB_SRM ON GYDMB(SRM) tablespace JZGLXT;
CREATE INDEX IND_GYDMB_BZ ON GYDMB(BZ) tablespace JZGLXT;
CREATE SEQUENCE SEQ_GYDMB_DMXH START WITH 1;

/*
CREATE SEQUENCE SEQ_GYDMB_CBZD START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_BRQX START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_JZFQ START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_CYBZ START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_ZY START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_LQQX START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_LQBZ START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_LQQX0 START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_ZLYY START WITH 1;
CREATE SEQUENCE SEQ_GYDMB_ZYKS START WITH 1;
*/

/*
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',1,'工人','GR');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',2,'农民','NM');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',3,'干部','GB');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',4,'教师','JS');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',5,'儿童','ET');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',6,'学生','XS');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',7,'现役军人','XYJR');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',8,'无业人员','WYRY');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('ZY',9,'退休','TX');

INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',1,'留观','LG');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',2,'留抢','LQ');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',3,'住院','ZY');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',4,'出院','CY');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',5,'手术','SS');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',6,'转院','ZY');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('BRQX',7,'死亡','SW');


INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('LQQX',1,'复苏室','ZY');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('LQQX',2,'抢救室','SW');

INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('LQQX0',1,'住院','ZY');
INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
VALUES('LQQX0',2,'出院','SW');

INSERT INTO GYDMB(DMLB,DMXH,DMMC,SRM)
select 'CBZD',code,NAME,SRM1 
from gy_jbdm where code > 11000 and ksdm = '1010000';

COMMIT;
*/