--统计条件表
DROP TABLE tjtjb_temp;
CREATE TABLE tjtjb_temp
(
  JLXH          NUMBER(10)    NOT NULL,  --记录序号
  XTXH          NUMBER(2)     NOT NULL,  --系统序号
  DATAOBJECT    VARCHAR2(20)  NOT NULL,  --源数据窗口对象
  TJTJMC        VARCHAR2(100) NOT NULL,  --统计条件名称
  YHDM		VARCHAR2(5)   NULL,      --用户代码
  CONSTRAINT PK_TJTJB_TEMP PRIMARY KEY(JLXH)
);
CREATE INDEX IDX_TJTJB_TEMP_XTXH_DATAOBJECT ON TJTJB_TEMP(XTXH,DATAOBJECT) ;