--急诊创伤评估登记表（删除的记录临时存放）
DROP TABLE JZ_JZCSPGDJB_TEMP;
CREATE TABLE JZ_JZCSPGDJB_TEMP
(
  JLXH   NUMBER(9)     NOT NULL,    --记录序号
  YJJLXH VARCHAR2(9)   NOT NULL,    --预检记录序号
  JZKH   VARCHAR2(20)  NULL,        --就诊卡号
  DJRQ   DATE          NOT NULL,    --登记日期
  DJR    VARCHAR2(10)  NOT NULL,    --登记人
  XGRQ   DATE          NULL,        --最后修改日期
  XGR    VARCHAR2(10)  NULL,        --最后修改人
  BRXM   VARCHAR2(20)  NOT NULL,    --病人姓名
  XB     INTEGER       NOT NULL,    --性别
  CSRQ   DATE          NULL,        --出生日期
  CRAMS  NUMBER(2)     NULL,        --CRAMS评分
  RTS    NUMBER(2)     NULL,        --DTS评分
  GCS    NUMBER(2)     NULL,        --GCS评分
  RTTBZ	 VARCHAR2(300) NULL,        --人体图标志
  MBXH   NUMBER(2)     NOT NULL,    --模板序号
  SCRQ   DATE          NOT NULL,    --删除日期
  SCR    VARCHAR2(10)  NOT NULL,    --删除人
  CONSTRAINT PK_JZ_JZCSPGDJB_TEMP PRIMARY KEY(JLXH)
);
CREATE SEQUENCE SEQ_JZ_JZCSPGDJB_TEMP_JLXH START WITH 1;

CREATE INDEX IDX_JZ_JZCSPGDJB_TEMP_JZKH ON JZ_JZCSPGDJB_TEMP(JZKH);
CREATE INDEX IDX_JZ_JZCSPGDJB_TEMP_DJRQ ON JZ_JZCSPGDJB_TEMP(DJRQ);
CREATE INDEX IDX_JZ_JZCSPGDJB_TEMP_BRXM ON JZ_JZCSPGDJB_TEMP(BRXM);  