--急诊创伤评估表模板
DROP TABLE JZ_JZCSPGBMB;
CREATE TABLE JZ_JZCSPGBMB
(
  JLXH     VARCHAR2(9)   NOT NULL,    --记录序号
  MBXH     NUMBER(2)     NOT NULL,    --模板序号
  PGCSDM   VARCHAR2(10)  NOT NULL,    --评估参数代码
  PGCSMC   VARCHAR2(20)  NOT NULL,    --评估参数名称
  CONSTRAINT PK_JZ_JZCSPGBMB PRIMARY KEY(JLXH)
);
CREATE SEQUENCE SEQ_JZ_JZCSPGBMB_JLXH START WITH 1;
CREATE INDEX IDX_JZ_JZCSPGBMB_PGCSDM ON JZ_JZCSPGBMB(PGCSDM);
CREATE INDEX IDX_JZ_JZCSPGBMB_PGCSMC ON JZ_JZCSPGBMB(PGCSMC);