--急诊创伤评估登记表
CREATE TABLE JZ_JZRYPGDJB
(
  JLXH   NUMBER(9)     NOT NULL,    --记录序号
  YJJLXH VARCHAR2(9)   NOT NULL,    --预检记录序号
  JZKH   VARCHAR2(20)  NULL,        --就诊卡号
  DJRQ   DATE          NOT NULL,    --登记日期
  DJR    VARCHAR2(10)  NOT NULL,    --登记人
  XGRQ   DATE          NULL,        --最后修改日期
  XGR    VARCHAR2(10)  NULL,        --最后修改人
  BRXM   VARCHAR2(20)  NOT NULL,    --病人姓名
  XB     INTEGER       NOT NULL,    --性别
  CSRQ   DATE          NULL,        --出生日期
  MBXH   NUMBER(2)     NOT NULL,    --模板序号
  CONSTRAINT PK_JZ_JZRYPGDJB PRIMARY KEY(JLXH)
);
CREATE SEQUENCE SEQ_JZ_JZRYPGDJB_JLXH START WITH 1;
CREATE UNIQUE INDEX UIDX_JZ_JZRYPGDJB_YJJLXH ON JZ_JZRYPGDJB(YJJLXH);
CREATE INDEX IDX_JZ_JZRYPGDJB_JZKH ON JZ_JZRYPGDJB(JZKH);
CREATE INDEX IDX_JZ_JZRYPGDJB_DJRQ ON JZ_JZRYPGDJB(DJRQ);
CREATE INDEX IDX_JZ_JZRYPGDJB_BRXM ON JZ_JZRYPGDJB(BRXM);  