select c.bah "病案号",
       c.brxm "病人姓名",
       c.xb "性别",
       jzs.uf_get_age(c.csrq,c.rysj,1) "入院年龄",
       c.rysj "预检时间",
       c.rytj "入院途径",
       c.rytjmx "入院途径说明",
       c.ksmc "分诊科室",
       c.hzksmc "会诊科室",
       c.cbzd "主诉/症状",
       c.jzfq "急诊分区",
       c.yjfj "预检分级",
       c.ghsj "挂号时间",
       c.jzsj "诊间就诊时间",
       a.lqsj "留抢时间",
       a.lqzd "留抢诊断",
       a.lqqx "留抢去向",
       a.ksmc "留抢科室",
       b.lqsj "离抢时间",
       b.lqqx "离抢去向",
       b.lqqxmx "离抢去向说明",
       (select sqrq from zjhis.zj_zysqd aa,zjhis.gy_brjbxxk bb where aa.jzkh = bb.jzkh and bb.bah = c.bah and sqrq between c.rysj and b.lqsj + 1 and rownum = 1) "开具住院申请单时间",
       b.ksmc "入住病区",
       (select admiss_date from zjhis2.zy_patient_information where bah = c.bah and admiss_date between c.rysj and b.lqsj + 1 and rownum = 1) "入院时间",
       (select cwfp_date from zjhis2.zy_patient_information where bah = c.bah and admiss_date between c.rysj and b.lqsj + 1 and rownum = 1) "床位分配时间",
       b.zytj "转运途径",
       b.zytjmx "转运途径说明",
       round((c.ghsj - c.rysj)*24*60,2) "挂号-预检时间差",
       round((c.jzsj - c.ghsj)*24*60,2) "就诊-挂号时间差",
       round((a.lqsj - c.rysj)*24*60,2) "留抢-预检时间差",
       round((b.lqsj - a.lqsj)*24*60,2) "离抢-留抢时间差",
       round(((select sqrq from zjhis.zj_zysqd aa,zjhis.gy_brjbxxk bb where aa.jzkh = bb.jzkh and bb.bah = c.bah and sqrq between c.rysj and b.lqsj + 1 and rownum = 1) - a.lqsj)*24*60,2) "开具住院申请单-留抢时间差",
       round(((select admiss_date from zjhis2.zy_patient_information where bah = c.bah and admiss_date between c.rysj and b.lqsj + 1 and rownum = 1) - a.lqsj)*24*60,2) "入院-留抢时间差",
       round(((select admiss_date from zjhis2.zy_patient_information where bah = c.bah and admiss_date between c.rysj and b.lqsj + 1 and rownum = 1) - (select sqrq from zjhis.zj_zysqd aa,zjhis.gy_brjbxxk bb where aa.jzkh = bb.jzkh and bb.bah = c.bah and sqrq between c.rysj and b.lqsj + 1 and rownum = 1))*24*60,2) "入院-开具住院申请单时间差",
       round(((select cwfp_date from zjhis2.zy_patient_information where bah = c.bah and admiss_date between c.rysj and b.lqsj + 1 and rownum = 1) - (select admiss_date from zjhis2.zy_patient_information where bah = c.bah and admiss_date between c.rysj and b.lqsj + 1 and rownum = 1))*24*60,2) "分配床位-入院时间差"
from jzs.jz_jzlqxxdjb a,jzs.jz_jzlqxxdjb0 b,jzs.jz_jzyjbrdjb c
where a.yjjlxh = b.yjjlxh
and a.yjjlxh = c.jlxh
and b.lqsj between to_date('20130201','yyyymmdd') and trunc(sysdate)
and a.lqqx <> '诊疗室';